package exceptions;

/**
 * Created by daan.vanbeek on 15-12-16.
 */
public class InvalidCoordinateException extends Exception {
    /**
	 * Autogenerated to remove warning.
	 */
	private static final long serialVersionUID = -3201761568174113313L;

	public InvalidCoordinateException(String message) {
        super(message);
    }
}
