package exceptions;

public class InvalidCommandLengthException extends Exception {
	/**
	 * Autogenerated.
	 */
	private static final long serialVersionUID = -8082621097429528852L;

	public InvalidCommandLengthException() {
	}

	public InvalidCommandLengthException(String message) {
		super(message);
	}

}
