package exceptions;

public class InvalidBoardSizeException extends Exception {
	/**
	 * Autogenerated.
	 */
	private static final long serialVersionUID = -6783045105024650149L;

	public InvalidBoardSizeException() {
		super();
	}

	public InvalidBoardSizeException(String message) {
		super(message);
	}

	public InvalidBoardSizeException(int boardSize) {
		super(boardSize + " is not a valid boardsize. Should be between 5 and 19.");
	}

}
