package exceptions;

public class KoException extends Exception {
	/**
	 * Autogenerated.
	 */
	private static final long serialVersionUID = -4299109061573293477L;

	public KoException() {
	}

	public KoException(String message) {
		super(message);
	}
}
