package exceptions;

public class NotYourTurnException extends Exception {
	/**
	 * Autogenerated.
	 */
	private static final long serialVersionUID = 3019720644874858242L;

	public NotYourTurnException() {
	}

	public NotYourTurnException(String message) {
		super(message);
	}



}
